/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginIndexImport } from './routes/auth/login/index'
import { Route as VitalUserIdMapImport } from './routes/vital/$userId/map'
import { Route as VitalUserIdDashboardImport } from './routes/vital/$userId/dashboard'
import { Route as VitalUserIdDashboardIndexImport } from './routes/vital/$userId/dashboard/index'
import { Route as AuthLoginForgotPasswordIndexImport } from './routes/auth/login/forgot-password/index'
import { Route as VitalUserIdGameLevelImport } from './routes/vital/$userId/game/$level'
import { Route as AuthLoginForgotPasswordVerifyImport } from './routes/auth/login/forgot-password/verify'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const VitalUserIdMapRoute = VitalUserIdMapImport.update({
  id: '/vital/$userId/map',
  path: '/vital/$userId/map',
  getParentRoute: () => rootRoute,
} as any)

const VitalUserIdDashboardRoute = VitalUserIdDashboardImport.update({
  id: '/vital/$userId/dashboard',
  path: '/vital/$userId/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const VitalUserIdDashboardIndexRoute = VitalUserIdDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VitalUserIdDashboardRoute,
} as any)

const AuthLoginForgotPasswordIndexRoute =
  AuthLoginForgotPasswordIndexImport.update({
    id: '/login/forgot-password/',
    path: '/login/forgot-password/',
    getParentRoute: () => AuthRoute,
  } as any)

const VitalUserIdGameLevelRoute = VitalUserIdGameLevelImport.update({
  id: '/vital/$userId/game/$level',
  path: '/vital/$userId/game/$level',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginForgotPasswordVerifyRoute =
  AuthLoginForgotPasswordVerifyImport.update({
    id: '/login/forgot-password/verify',
    path: '/login/forgot-password/verify',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/vital/$userId/dashboard': {
      id: '/vital/$userId/dashboard'
      path: '/vital/$userId/dashboard'
      fullPath: '/vital/$userId/dashboard'
      preLoaderRoute: typeof VitalUserIdDashboardImport
      parentRoute: typeof rootRoute
    }
    '/vital/$userId/map': {
      id: '/vital/$userId/map'
      path: '/vital/$userId/map'
      fullPath: '/vital/$userId/map'
      preLoaderRoute: typeof VitalUserIdMapImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/auth/login/forgot-password/verify': {
      id: '/auth/login/forgot-password/verify'
      path: '/login/forgot-password/verify'
      fullPath: '/auth/login/forgot-password/verify'
      preLoaderRoute: typeof AuthLoginForgotPasswordVerifyImport
      parentRoute: typeof AuthImport
    }
    '/vital/$userId/game/$level': {
      id: '/vital/$userId/game/$level'
      path: '/vital/$userId/game/$level'
      fullPath: '/vital/$userId/game/$level'
      preLoaderRoute: typeof VitalUserIdGameLevelImport
      parentRoute: typeof rootRoute
    }
    '/auth/login/forgot-password/': {
      id: '/auth/login/forgot-password/'
      path: '/login/forgot-password'
      fullPath: '/auth/login/forgot-password'
      preLoaderRoute: typeof AuthLoginForgotPasswordIndexImport
      parentRoute: typeof AuthImport
    }
    '/vital/$userId/dashboard/': {
      id: '/vital/$userId/dashboard/'
      path: '/'
      fullPath: '/vital/$userId/dashboard/'
      preLoaderRoute: typeof VitalUserIdDashboardIndexImport
      parentRoute: typeof VitalUserIdDashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLoginForgotPasswordVerifyRoute: typeof AuthLoginForgotPasswordVerifyRoute
  AuthLoginForgotPasswordIndexRoute: typeof AuthLoginForgotPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLoginForgotPasswordVerifyRoute: AuthLoginForgotPasswordVerifyRoute,
  AuthLoginForgotPasswordIndexRoute: AuthLoginForgotPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface VitalUserIdDashboardRouteChildren {
  VitalUserIdDashboardIndexRoute: typeof VitalUserIdDashboardIndexRoute
}

const VitalUserIdDashboardRouteChildren: VitalUserIdDashboardRouteChildren = {
  VitalUserIdDashboardIndexRoute: VitalUserIdDashboardIndexRoute,
}

const VitalUserIdDashboardRouteWithChildren =
  VitalUserIdDashboardRoute._addFileChildren(VitalUserIdDashboardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/vital/$userId/dashboard': typeof VitalUserIdDashboardRouteWithChildren
  '/vital/$userId/map': typeof VitalUserIdMapRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/login/forgot-password/verify': typeof AuthLoginForgotPasswordVerifyRoute
  '/vital/$userId/game/$level': typeof VitalUserIdGameLevelRoute
  '/auth/login/forgot-password': typeof AuthLoginForgotPasswordIndexRoute
  '/vital/$userId/dashboard/': typeof VitalUserIdDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
  '/vital/$userId/map': typeof VitalUserIdMapRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/login/forgot-password/verify': typeof AuthLoginForgotPasswordVerifyRoute
  '/vital/$userId/game/$level': typeof VitalUserIdGameLevelRoute
  '/auth/login/forgot-password': typeof AuthLoginForgotPasswordIndexRoute
  '/vital/$userId/dashboard': typeof VitalUserIdDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
  '/vital/$userId/dashboard': typeof VitalUserIdDashboardRouteWithChildren
  '/vital/$userId/map': typeof VitalUserIdMapRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/login/forgot-password/verify': typeof AuthLoginForgotPasswordVerifyRoute
  '/vital/$userId/game/$level': typeof VitalUserIdGameLevelRoute
  '/auth/login/forgot-password/': typeof AuthLoginForgotPasswordIndexRoute
  '/vital/$userId/dashboard/': typeof VitalUserIdDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/register'
    | '/auth/'
    | '/vital/$userId/dashboard'
    | '/vital/$userId/map'
    | '/auth/login'
    | '/auth/login/forgot-password/verify'
    | '/vital/$userId/game/$level'
    | '/auth/login/forgot-password'
    | '/vital/$userId/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/register'
    | '/auth'
    | '/vital/$userId/map'
    | '/auth/login'
    | '/auth/login/forgot-password/verify'
    | '/vital/$userId/game/$level'
    | '/auth/login/forgot-password'
    | '/vital/$userId/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/register'
    | '/auth/'
    | '/vital/$userId/dashboard'
    | '/vital/$userId/map'
    | '/auth/login/'
    | '/auth/login/forgot-password/verify'
    | '/vital/$userId/game/$level'
    | '/auth/login/forgot-password/'
    | '/vital/$userId/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  VitalUserIdDashboardRoute: typeof VitalUserIdDashboardRouteWithChildren
  VitalUserIdMapRoute: typeof VitalUserIdMapRoute
  VitalUserIdGameLevelRoute: typeof VitalUserIdGameLevelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  VitalUserIdDashboardRoute: VitalUserIdDashboardRouteWithChildren,
  VitalUserIdMapRoute: VitalUserIdMapRoute,
  VitalUserIdGameLevelRoute: VitalUserIdGameLevelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/vital/$userId/dashboard",
        "/vital/$userId/map",
        "/vital/$userId/game/$level"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/register",
        "/auth/",
        "/auth/login/",
        "/auth/login/forgot-password/verify",
        "/auth/login/forgot-password/"
      ]
    },
    "/auth/register": {
      "filePath": "auth/register.tsx",
      "parent": "/auth"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/vital/$userId/dashboard": {
      "filePath": "vital/$userId/dashboard.tsx",
      "children": [
        "/vital/$userId/dashboard/"
      ]
    },
    "/vital/$userId/map": {
      "filePath": "vital/$userId/map.tsx"
    },
    "/auth/login/": {
      "filePath": "auth/login/index.tsx",
      "parent": "/auth"
    },
    "/auth/login/forgot-password/verify": {
      "filePath": "auth/login/forgot-password/verify.tsx",
      "parent": "/auth"
    },
    "/vital/$userId/game/$level": {
      "filePath": "vital/$userId/game/$level.tsx"
    },
    "/auth/login/forgot-password/": {
      "filePath": "auth/login/forgot-password/index.tsx",
      "parent": "/auth"
    },
    "/vital/$userId/dashboard/": {
      "filePath": "vital/$userId/dashboard/index.tsx",
      "parent": "/vital/$userId/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
